services:
  shlink-web:
    image: shlinkio/shlink-web-client:latest
    container_name: shlink-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SHLINK_SERVER_URL=http://localhost:8081
      - SHLINK_SERVER_API_KEY=HXIWazWnH4QFemrZpe6ABkMoDlgLE5Yg
      - SHLINK_SERVER_NAME=Shlink Server
